---
action:
  exec:
    args: 
      - az
      - spring
      - app
      - deploy
      - --resource-group
      - '{{resource-group}}'
      - --service
      - 'si-{{user-name}}'
      - --name 
      - '{{project-name}}'      
      - --artifact-path 
      - '{{artifact-path}}'
---